version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: setup/Dockerfile
    env_file:
      - ../config/.env
    volumes:
      - ../src:/app/src
      - ../config:/app/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]